
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 16 04:51:54 VET 2019
//----------------------------------------------------

package Tiny;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 18;
  public static final int MI = 30;
  public static final int MAI = 32;
  public static final int CONJ = 35;
  public static final int LPAREN = 19;
  public static final int SEMI = 21;
  public static final int REPEAT = 6;
  public static final int INT = 39;
  public static final int ARRAY = 22;
  public static final int FOR = 28;
  public static final int MINUS = 16;
  public static final int RCOR = 24;
  public static final int WRITE = 9;
  public static final int RPAREN = 20;
  public static final int LT = 14;
  public static final int BOOL = 38;
  public static final int COMMA = 37;
  public static final int ENDFOR = 29;
  public static final int UNTIL = 7;
  public static final int NUM = 11;
  public static final int DIS = 33;
  public static final int PLUS = 15;
  public static final int DISY = 34;
  public static final int ASSIGN = 12;
  public static final int IF = 2;
  public static final int ID = 10;
  public static final int ENDWHILE = 27;
  public static final int EOF = 0;
  public static final int SIZE = 25;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int TIMES = 17;
  public static final int NEG = 36;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int WHILE = 26;
  public static final int LCOR = 23;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int GT = 31;
}

